#!/usr/bin/env bash

MAIN_CLASS="com.oracle.truffle.sl.launcher.SLMain"
JDK_HOME="/graalvm-ce-java8-20.3.0/"
JAVA_HOME="$JDK_HOME/bin/java"

JAVA_ARGS=("-server" "-XX:+UnlockExperimentalVMOptions" "-XX:+EnableJVMCI" "-XX:+EagerJVMCI" "-XX:-UseJVMCINativeLibrary" "-XX:-UseJVMCIClassLoader" "-d64" "-ea" "-Djava.awt.headless=true" "-XX:-UseCompressedOops")
GRAAL_ARGS=("-Dgraal.DebugStubsAndSnippets=true" "-XX:-TraceDeoptimization" "-Dgraal.GenLoopSafepoints=false" "-Dgraal.ShowConfiguration=verbose")


PROGRAM_ARGS=()

for opt in "$@"
    do
      case $opt in
        -dump)
            JAVA_ARGS+=("-Dgraal.Dump=Truffle:1" "-Dgraal.TruffleBackgroundCompilation=false" "-Dgraal.PrintGraph=Network"  "-Dgraal.TraceTruffleCompilation=true" "-Dgraal.TraceTruffleCompilationDetails=true") ;;
        -disassemble)
            JAVA_ARGS+=("-Dgraal.PrintCFG=true" "-Dgraal.Dump" "-XX:+UnlockDiagnosticVMOptions" "-XX:CompileCommand=print,*LuthPipelineRootNode" "-XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot" "-Dgraal.TruffleBackgroundCompilation=false" "-Dgraal.TraceTruffleCompilation=true" "-Dgraal.TraceTruffleCompilationDetails=true") ;;
        *)
            PROGRAM_ARGS+=("$opt") ;;
      esac
    done

#Xbootclasspath="-Xbootclasspath/p:conf/target/classes:compiler/target/classes:operator/target/classes:storage/target/classes:typesystem/target/classes:javadriver/target/classes:js-driver/target/classes:benchmark/target/classes"
Xbootclasspath="-Xbootclasspath/p:compiler/target/classes:conf/target/classes:operator/target/classes:storage/target/classes:typesystem/target/classes:javadriver/target/classes:js-driver/target/classes:benchmark/target/classes:/root/.m2/repository/org/apache/arrow/arrow-memory-unsafe/2.0.0/arrow-memory-unsafe-2.0.0.jar:/root/.m2/repository/org/apache/arrow/arrow-memory-core/2.0.0/arrow-memory-core-2.0.0.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/root/.m2/repository/org/apache/arrow/arrow-vector/2.0.0/arrow-vector-2.0.0.jar:/root/.m2/repository/org/apache/arrow/arrow-format/2.0.0/arrow-format-2.0.0.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.8/jackson-annotations-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar:/root/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/root/.m2/repository/io/netty/netty-common/4.1.48.Final/netty-common-4.1.48.Final.jar:/root/.m2/repository/com/google/flatbuffers/flatbuffers-java/1.9.0/flatbuffers-java-1.9.0.jar"
#ClassPath="-classpath /root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/charsets.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/cldrdata.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/dnsns.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/jaccess.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/localedata.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/nashorn.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/sunec.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/sunjce_provider.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/sunpkcs11.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/ext/zipfs.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/jce.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/jsse.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/jvmci-services.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/management-agent.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/resources.jar:/root/tools/java/graalvm-ce-java8-20.1.0/jre/lib/rt.jar:/root/projects/luth-org/luth/benchmark/target/classes:/root/projects/luth-org/luth/operator/target/classes:/root/.m2/repository/org/graalvm/truffle/truffle-api/20.1.0/truffle-api-20.1.0.jar:/root/.m2/repository/org/graalvm/compiler/compiler/20.1.0/compiler-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/graal-sdk/20.1.0/graal-sdk-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/launcher-common/20.1.0/launcher-common-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/polyglot-tck/20.1.0/polyglot-tck-20.1.0.jar:/root/projects/luth-org/luth/typesystem/target/classes:/root/.m2/repository/com/google/auto/service/auto-service/1.0-rc2/auto-service-1.0-rc2.jar:/root/.m2/repository/com/google/auto/auto-common/0.3/auto-common-0.3.jar:/root/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/root/projects/luth-org/luth/compiler/target/classes:/root/projects/luth-org/luth/storage/target/classes:/root/projects/luth-org/luth/javadriver/target/classes:/root/.m2/repository/org/antlr/antlr4/4.7.2/antlr4-4.7.2.jar:/root/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:/root/.m2/repository/org/antlr/ST4/4.1/ST4-4.1.jar:/root/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/root/.m2/repository/com/ibm/icu/icu4j/61.1/icu4j-61.1.jar:/root/.m2/repository/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:/root/projects/luth-org/luth/js-driver/target/classes:/root/tools/java/graalvm-ce-java8-20.0.0/jre/languages/python/graalpython.jar:/root/tools/java/openjdk1.8.0_jvmci/jre/lib/jvmci/jvmci-api.jar:/root/tools/java/openjdk1.8.0_jvmci/jre/lib/jvmci/jvmci-hotspot.jar:/root/tools/java/openjdk1.8.0_jvmci/jre/lib/jvmci-services.jar"
#ClassPath="-classpath /root/projects/luth-org/luth/benchmark/target/classes:/root/projects/luth-org/luth/operator/target/classes:/root/.m2/repository/org/graalvm/truffle/truffle-api/20.1.0/truffle-api-20.1.0.jar:/root/.m2/repository/org/graalvm/compiler/compiler/20.1.0/compiler-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/graal-sdk/20.1.0/graal-sdk-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/launcher-common/20.1.0/launcher-common-20.1.0.jar:/root/.m2/repository/org/graalvm/sdk/polyglot-tck/20.1.0/polyglot-tck-20.1.0.jar:/root/projects/luth-org/luth/typesystem/target/classes:/root/.m2/repository/com/google/auto/service/auto-service/1.0-rc2/auto-service-1.0-rc2.jar:/root/.m2/repository/com/google/auto/auto-common/0.3/auto-common-0.3.jar:/root/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/root/projects/luth-org/luth/compiler/target/classes:/root/projects/luth-org/luth/storage/target/classes:/root/projects/luth-org/luth/javadriver/target/classes:/root/.m2/repository/org/antlr/antlr4/4.7.2/antlr4-4.7.2.jar:/root/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:/root/.m2/repository/org/antlr/ST4/4.1/ST4-4.1.jar:/root/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/root/.m2/repository/com/ibm/icu/icu4j/61.1/icu4j-61.1.jar:/root/.m2/repository/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:/root/projects/luth-org/luth/js-driver/target/classes:/root/tools/java/graalvm-ce-java8-20.0.0/jre/languages/python/graalpython.jar"

FatJar="benchmark/target/sl-launcher.jar"
GraalPhython="$JDK_HOME/jre/languages/python/graalpython.jar"
ClassPath="-classpath $FatJar:benchmark/target/classes:operator/target/classes::typesystem/target/classes:compiler/target/classes:storage/target/classes:javadriver/target/classes:js-driver/target/classes:$GraalPhython"

echo "$JAVA_HOME" "${JAVA_ARGS[@]}" "${GRAAL_ARGS[@]}" $Xbootclasspath $ClassPath de.tub.dima.luth.benchmark.layout.LayoutBenchmarkRunner "${PROGRAM_ARGS[@]}" -luth.home=~ -js.home=~ --tool:regex
numactl -N 1 -m 1  "$JAVA_HOME" "${JAVA_ARGS[@]}" "${GRAAL_ARGS[@]}" $Xbootclasspath $ClassPath de.tub.dima.luth.benchmark.layout.LayoutBenchmarkRunner "${PROGRAM_ARGS[@]}" -luth.home=~ -js.home=~ --tool:regex